### ISSUE TITLE
Heroku Support Not Working Properly

### ISSUE THREAD

**Issue by gunasekharravilla** [MrBotDeveloper/PDF-Bot#25]
Heroku deploy button is working for you 

please help to deploy and link to telegram bot

**Comment by MrBotDeveloper** [comment]
Sorry not working as it needs Datastore on Google Cloud Platform (GCP).

**Comment by gunasekharravilla** [comment]
I did everything  I enabled gcp but after deploying in heroku it is showing  application error

**Comment by MrBotDeveloper** [comment]
**Ok bro please talk me**  [**@Mr_Pro_Noob**](https://t.me/Mr_Pro_Noob) as I am **mostly active** there.

**Comment by MrBotDeveloper** [comment]
Now fixed check now ....
