### ISSUE TITLE
GCP Credentials Error

### ISSUE THREAD

**Issue by sholoomail** [MrBotDeveloper/PDF-Bot#88]
hi.
i create a pdf bot on heruko and i het an error:
raise exceptions.DefaultCredentialsError(******http://localhost:3000/oauth2callback"]}} was not found.
how i fix it?

**Comment by MrBotDeveloper** [comment]
Can you provide me full logs??

**Comment by sholoomail** [comment]
> Can you pr2021-07-17T15:15:52.423993+00:00 app[worker.1]:     _, project = google.auth.default()
2021-07-17T15:15:52.423995+00:00 app[worker.1]:   File "/venv/lib/python3.9/site-packages/google/auth/_default.py", line 454, in default
2021-07-17T15:15:52.424278+00:00 app[worker.1]:     credentials, project_id = checker()
2021-07-17T15:15:52.424280+00:00 app[worker.1]:   File "/venv/lib/python3.9/site-packages/google/auth/_default.py", line 221, in _get_explicit_environ_credentials
2021-07-17T15:15:52.424477+00:00 app[worker.1]:     credentials, project_id = load_credentials_from_file(
2021-07-17T15:15:52.424503+00:00 app[worker.1]:   File "/venv/lib/python3.9/site-packages/google/auth/_default.py", line 107, in load_credentials_from_file
2021-07-17T15:15:52.424659+00:00 app[worker.1]:     raise exceptions.DefaultCredentialsError(
2021-07-17T15:15:52.424707+00:00 app[worker.1]: google.auth.exceptions.DefaultCredentialsError: File {"web":{"client_id":"863846464087-8t2glijtmos8o661l6jthjvj9sonihm2.apps.googleusercontent.com","project_id":"sholoopdfmanager","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"nF3pcWEvHkBKXN0CE9q5qtbn","redirect_uris":["http://localhost:3000/oauth2callback"]}} was not found.
2021-07-17T15:15:52.639016+00:00 heroku[worker.1]: Process exited with status 1
2021-07-17T15:15:52.713944+00:00 heroku[worker.1]: State changed from up to crashedovide me full logs??

**Comment by MrBotDeveloper** [comment]
Sir your GCP credentials are invalid...

**Comment by sholoomail** [comment]
> 
> 
> Sir your GCP credentials are invalid...

how to create a valid one?

**Comment by MrBotDeveloper** [comment]
https://github.com/MrBotDeveloper/PDF-Bot#getting-started

**Comment by MrBotDeveloper** [comment]
**You can also Take reference Of this Article =>** https://docs.aviatrix.com/HowTos/CreateGCloudAccount.html

**Comment by sholoomail** [comment]
> 
> 
> **You can also Take reference Of this Article =>** https://docs.aviatrix.com/HowTos/CreateGCloudAccount.html

my bot return error for localhost (redirect url)

**Comment by MrBotDeveloper** [comment]
**Sir follow the below steps to create a valid GCP Credentials File :-**

1. Firstly Go to https://console.cloud.google.com/project
2. Create a Project.
3. Open http://console.developers.google.com/project/_/apiui/credential And Click on Create Ceredinials then Click on Service Account.
4. Enter all the required values. [At the Service Accounts, enter a Service account name and click Create. For Service account permissions, select Project, Owner.]
5. Select a service account. Click the 3 skewer bar and select Create Key. Select JSON, click Create.
6. Click Create. The credential file will be downloaded to your local computer or Any Device your are Using. 
7. Upload the Project Credential file to the bots private repo. 
8. Then Open https://console.cloud.google.com/datastore/setup .
9. And enable the FireStore Database. 
10. Now open https://console.cloud.google.com/iam-admin/iam .
11. And set the service account's role to owner. **Note: If you can't see your service account in the list click on Add and add your service account with Owner as Role.**
12. Now Deploy your bot and set ```GOOGLE_APPLICATION_CREDENTIALS``` var with value as the File Name of the Ceredinials Json you uploaded in the repo in Step 7.
13. Congratulations 🎉 your bot has been Successfully Started 😊 So enjoy 🤗.

```alert.txt
⚠️ I will Recommend you to Use Only Google Chrome for generating Ceredinials Json as some browsers will not start the Download of the Json file in the Step 6 ⚠️
```

**Don't Forget to Star 🌟 Repo if ❤️ The Repo and Follow [Me](https://github.com/MrBotDeveloper) to show your ❤️.**

**Comment by MrBotDeveloper** [comment]
**Sir kindly 🤗 follow the below steps to create a valid GCP Credentials File :-**

1. Firstly Go to https://console.cloud.google.com/project
2. Create a Project.
3. Open http://console.developers.google.com/project/_/apiui/credential And Click on Create Ceredinials then Click on Service Account.
4. Enter all the required values. [At the Service Accounts, enter a Service account name and click Create. For Service account permissions, select Project, Owner.]
5. Select a service account. Click the 3 skewer bar and select Create Key. Select JSON, click Create.
6. Click Create. The credential file will be downloaded to your local computer or Any Device your are Using. 
7. Upload the Project Credential file to the bots private repo. 
8. Then Open https://console.cloud.google.com/datastore/setup .
9. And enable the FireStore Database. 
10. Now open https://console.cloud.google.com/iam-admin/iam .
11. And set the service account's role to owner. **Note: If you can't see your service account in the list click on Add and add your service account with Owner as Role.**
12. Now Deploy your bot and set ```GOOGLE_APPLICATION_CREDENTIALS``` var with value as the File Name of the Ceredinials Json you uploaded in the repo in Step 7.
13. Congratulations 🎉 your bot has been Successfully Started 😊 So enjoy 🤗.

```alert.txt
⚠️ I will Recommend you to Use Only Google Chrome for generating Ceredinials Json as some browsers will not start the Download of the Json file in the Step 6 ⚠️
```

**Don't Forget to Star 🌟 Repo if ❤️ The Repo and Follow [Me](https://github.com/MrBotDeveloper) to show your ❤️.**
